apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-shopping-app-client
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: shopping-app-client
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: shopping-app-client
    spec:
      containers:
      - name: shopping-app-client
        # Run this image
        image: saurabhwarhade/shoppingappclient:v3.2
        env:
        - name: PORT
          valueFrom:
           configMapKeyRef: 
            name: server-config
            key: server-url




---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-my-shopping-app-client
spec:
  type: nodePort
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 5173
      targetPort: 5173
      nodePort: 30100
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: shopping-app-client
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer



